# Generated by Django 6.0.5 on 2026-07-29 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Site root URL, e.g. https://example.com')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('detected_platform', models.CharField(blank=True, help_text='e.g. ghost, wordpress, unknown', max_length=50)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('ok', 'Synced'), ('error', 'Error')], default='pending', max_length=20)),
                ('sync_error', models.TextField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ghost_content_api', 'Ghost Content API'), ('ghost_geo', 'Ghost GEO (llms.txt / .md)'), ('rss', 'RSS / Atom feed'), ('sitemap_crawl', 'Sitemap crawl')], max_length=30)),
                ('config', models.JSONField(blank=True, default=dict, help_text="Adapter config, e.g. {'api_key': ...} or {'feed_url': ...}")),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower = higher fidelity, used first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='websites.website')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_guid', models.CharField(help_text='Stable identifier from the source (Ghost id, RSS guid, or URL)', max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=500)),
                ('url', models.URLField(max_length=1000)),
                ('excerpt', models.TextField(blank=True)),
                ('markdown_body', models.TextField(blank=True)),
                ('html_body', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_promoted_at', models.DateTimeField(blank=True, help_text='Last time a campaign promoted this post', null=True)),
                ('promo_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='websites.website')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='website_assets/')),
                ('alt_text', models.TextField(blank=True)),
                ('is_feature', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='websites.blogpost')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('blog_post', 'source_url'), name='unique_image_per_post')],
            },
        ),
        migrations.AddConstraint(
            model_name='website',
            constraint=models.UniqueConstraint(fields=('user', 'url'), name='unique_website_per_user'),
        ),
        migrations.AddConstraint(
            model_name='contentsource',
            constraint=models.UniqueConstraint(fields=('website', 'kind'), name='unique_source_kind_per_website'),
        ),
        migrations.AddConstraint(
            model_name='blogpost',
            constraint=models.UniqueConstraint(fields=('website', 'source_guid'), name='unique_post_per_website'),
        ),
    ]
