# Generated by Django 6.0.5 on 2026-07-29 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threads_user_id', models.CharField(max_length=100)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('access_token', models.TextField(help_text='Long-lived Threads token (refreshable)')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
