# Generated by Django 6.0.5 on 2026-07-29 09:11

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadsaccount',
            name='access_token',
            field=core.fields.EncryptedTextField(help_text='Long-lived Threads token (refreshable)'),
        ),
    ]
