# Generated by Django 6.0.1 on 2026-01-30 09:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pixelfed', '0001_initial'),
        ('postflow', '0027_backfill_analytics_post_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='MastodonPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastodon_post_id', models.CharField(db_index=True, help_text='Unique Mastodon post ID', max_length=100, unique=True)),
                ('instance_url', models.URLField(help_text='Mastodon instance URL (e.g., https://mastodon.social)', max_length=255)),
                ('username', models.CharField(help_text='Username of the poster (without @)', max_length=100)),
                ('content', models.TextField(blank=True, help_text='Post content/text')),
                ('media_url', models.URLField(blank=True, help_text='Primary image, video, or audio URL', max_length=500)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('gifv', 'GIF Video'), ('audio', 'Audio'), ('unknown', 'Unknown')], default='image', help_text='Type of media in the post', max_length=20)),
                ('post_url', models.URLField(help_text='Full URL to the post on Mastodon', max_length=500)),
                ('posted_at', models.DateTimeField(db_index=True, help_text='When the post was published on Mastodon')),
                ('edited_at', models.DateTimeField(blank=True, help_text='When the post was last edited (if edited)', null=True)),
                ('last_fetched_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last time analytics were fetched')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created in PostFlow')),
                ('visibility', models.CharField(default='public', help_text='Post visibility: public, unlisted, private, or direct', max_length=20)),
                ('language', models.CharField(blank=True, help_text='ISO 639-1 language code', max_length=10, null=True)),
                ('sensitive', models.BooleanField(default=False, help_text='Whether content has a content warning')),
                ('spoiler_text', models.CharField(blank=True, help_text='Content warning text', max_length=500, null=True)),
                ('in_reply_to_id', models.CharField(blank=True, help_text='Parent post ID if this is a reply', max_length=100, null=True)),
                ('in_reply_to_account_id', models.CharField(blank=True, help_text='Parent post author account ID', max_length=100, null=True)),
                ('api_replies_count', models.IntegerField(default=0, help_text='Reply count from API Status object')),
                ('api_reblogs_count', models.IntegerField(default=0, help_text='Reblog/boost count from API Status object')),
                ('api_favourites_count', models.IntegerField(default=0, help_text='Favourite/like count from API Status object')),
                ('account', models.ForeignKey(help_text='The Mastodon account that posted this', on_delete=django.db.models.deletion.CASCADE, related_name='mastodon_analytics_posts', to='pixelfed.mastodonaccount')),
                ('scheduled_post', models.ForeignKey(blank=True, help_text='Linked ScheduledPost if this was created via PostFlow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mastodon_analytics', to='postflow.scheduledpost')),
            ],
            options={
                'verbose_name': 'Mastodon Post',
                'verbose_name_plural': 'Mastodon Posts',
                'db_table': 'analytics_mastodon_post',
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='MastodonFavourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(help_text='Mastodon account ID of the favouriter', max_length=100)),
                ('username', models.CharField(help_text='Username of the favouriter (without @)', max_length=100)),
                ('display_name', models.CharField(blank=True, help_text='Display name of the favouriter', max_length=200)),
                ('favourited_at', models.DateTimeField(db_index=True, help_text='When the favourite occurred (estimated as first discovered time)')),
                ('first_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When we first discovered this favourite (for timeline estimation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created in PostFlow')),
                ('post', models.ForeignKey(help_text='The post that was favourited', on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='analytics_mastodon.mastodonpost')),
            ],
            options={
                'verbose_name': 'Mastodon Favourite',
                'verbose_name_plural': 'Mastodon Favourites',
                'db_table': 'analytics_mastodon_favourite',
                'ordering': ['-favourited_at'],
            },
        ),
        migrations.CreateModel(
            name='MastodonEngagementSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_favourites', models.IntegerField(db_index=True, default=0, help_text='Total number of favourites')),
                ('total_replies', models.IntegerField(default=0, help_text='Total number of replies')),
                ('total_reblogs', models.IntegerField(default=0, help_text='Total number of reblogs')),
                ('total_engagement', models.IntegerField(db_index=True, default=0, help_text='Sum of favourites + replies + reblogs')),
                ('engagement_rate', models.FloatField(blank=True, help_text='Engagement rate percentage (future: based on impressions)', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When these metrics were last updated')),
                ('post', models.OneToOneField(help_text='The post these metrics belong to', on_delete=django.db.models.deletion.CASCADE, related_name='engagement_summary', to='analytics_mastodon.mastodonpost')),
            ],
            options={
                'verbose_name': 'Mastodon Engagement Summary',
                'verbose_name_plural': 'Mastodon Engagement Summaries',
                'db_table': 'analytics_mastodon_engagement_summary',
            },
        ),
        migrations.CreateModel(
            name='MastodonReblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(help_text='Mastodon account ID of the reblogger', max_length=100)),
                ('username', models.CharField(help_text='Username of the reblogger (without @)', max_length=100)),
                ('display_name', models.CharField(blank=True, help_text='Display name of the reblogger', max_length=200)),
                ('reblogged_at', models.DateTimeField(db_index=True, help_text='When the reblog occurred (estimated as first discovered time)')),
                ('first_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When we first discovered this reblog (for timeline estimation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created in PostFlow')),
                ('post', models.ForeignKey(help_text='The post that was reblogged', on_delete=django.db.models.deletion.CASCADE, related_name='reblogs', to='analytics_mastodon.mastodonpost')),
            ],
            options={
                'verbose_name': 'Mastodon Reblog',
                'verbose_name_plural': 'Mastodon Reblogs',
                'db_table': 'analytics_mastodon_reblog',
                'ordering': ['-reblogged_at'],
            },
        ),
        migrations.CreateModel(
            name='MastodonReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_id', models.CharField(db_index=True, help_text='Unique Mastodon reply ID', max_length=100, unique=True)),
                ('account_id', models.CharField(help_text='Mastodon account ID of replier', max_length=100)),
                ('username', models.CharField(help_text='Username of replier (without @)', max_length=100)),
                ('display_name', models.CharField(blank=True, help_text='Display name of replier', max_length=200)),
                ('content', models.TextField(help_text='Reply text content')),
                ('in_reply_to_id', models.CharField(blank=True, help_text='ID of parent reply (for threading)', max_length=100, null=True)),
                ('replied_at', models.DateTimeField(db_index=True, help_text='When the reply was posted')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created in PostFlow')),
                ('post', models.ForeignKey(help_text='The post being replied to', on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='analytics_mastodon.mastodonpost')),
            ],
            options={
                'verbose_name': 'Mastodon Reply',
                'verbose_name_plural': 'Mastodon Replies',
                'db_table': 'analytics_mastodon_reply',
                'ordering': ['replied_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mastodonpost',
            index=models.Index(fields=['posted_at'], name='analytics_m_posted__a5a8fd_idx'),
        ),
        migrations.AddIndex(
            model_name='mastodonpost',
            index=models.Index(fields=['last_fetched_at'], name='analytics_m_last_fe_991c23_idx'),
        ),
        migrations.AddIndex(
            model_name='mastodonpost',
            index=models.Index(fields=['account', 'posted_at'], name='analytics_m_account_be446c_idx'),
        ),
        migrations.AddIndex(
            model_name='mastodonpost',
            index=models.Index(fields=['visibility'], name='analytics_m_visibil_ac46bf_idx'),
        ),
        migrations.AddIndex(
            model_name='mastodonpost',
            index=models.Index(fields=['in_reply_to_id'], name='analytics_m_in_repl_a45e3f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mastodonpost',
            unique_together={('instance_url', 'mastodon_post_id')},
        ),
        migrations.AddIndex(
            model_name='mastodonfavourite',
            index=models.Index(fields=['favourited_at'], name='analytics_m_favouri_499ba8_idx'),
        ),
        migrations.AddIndex(
            model_name='mastodonfavourite',
            index=models.Index(fields=['first_seen_at'], name='analytics_m_first_s_29e11a_idx'),
        ),
        migrations.AddIndex(
            model_name='mastodonfavourite',
            index=models.Index(fields=['username'], name='analytics_m_usernam_42a2f4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mastodonfavourite',
            unique_together={('post', 'account_id')},
        ),
        migrations.AddIndex(
            model_name='mastodonreblog',
            index=models.Index(fields=['reblogged_at'], name='analytics_m_reblogg_354fae_idx'),
        ),
        migrations.AddIndex(
            model_name='mastodonreblog',
            index=models.Index(fields=['first_seen_at'], name='analytics_m_first_s_d29f0b_idx'),
        ),
        migrations.AddIndex(
            model_name='mastodonreblog',
            index=models.Index(fields=['username'], name='analytics_m_usernam_72d10b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mastodonreblog',
            unique_together={('post', 'account_id')},
        ),
        migrations.AddIndex(
            model_name='mastodonreply',
            index=models.Index(fields=['replied_at'], name='analytics_m_replied_89e2df_idx'),
        ),
        migrations.AddIndex(
            model_name='mastodonreply',
            index=models.Index(fields=['username'], name='analytics_m_usernam_ebdb9d_idx'),
        ),
        migrations.AddIndex(
            model_name='mastodonreply',
            index=models.Index(fields=['in_reply_to_id'], name='analytics_m_in_repl_5ce5c1_idx'),
        ),
    ]
