# Generated by Django 6.0.1 on 2026-01-30 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_mastodon', '0001_initial'),
        ('mastodon_native', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastodonpost',
            name='account',
            field=models.ForeignKey(help_text='The Mastodon account that posted this', on_delete=django.db.models.deletion.CASCADE, related_name='mastodon_analytics_posts', to='mastodon_native.mastodonaccount'),
        ),
    ]
