# Generated by Django 6.0.1 on 2026-02-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_mastodon', '0002_alter_mastodonpost_account'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mastodonengagementsummary',
            index=models.Index(fields=['-total_engagement'], name='analytics_m_total_e_e9a2d0_idx'),
        ),
        migrations.AddIndex(
            model_name='mastodonengagementsummary',
            index=models.Index(fields=['-total_favourites'], name='analytics_m_total_f_65ce86_idx'),
        ),
        migrations.AddIndex(
            model_name='mastodonengagementsummary',
            index=models.Index(fields=['-total_replies'], name='analytics_m_total_r_d3b9d2_idx'),
        ),
        migrations.AddIndex(
            model_name='mastodonengagementsummary',
            index=models.Index(fields=['-total_reblogs'], name='analytics_m_total_r_b9f0f3_idx'),
        ),
        migrations.AddIndex(
            model_name='mastodonfavourite',
            index=models.Index(fields=['post', 'username'], name='analytics_m_post_id_1d6d05_idx'),
        ),
        migrations.AddIndex(
            model_name='mastodonreblog',
            index=models.Index(fields=['post', 'username'], name='analytics_m_post_id_974ac1_idx'),
        ),
        migrations.AddIndex(
            model_name='mastodonreply',
            index=models.Index(fields=['post', 'username'], name='analytics_m_post_id_3a13be_idx'),
        ),
    ]
