# Generated by Django 6.0.1 on 2026-01-30 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instagram', '0001_initial'),
        ('postflow', '0027_backfill_analytics_post_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_media_id', models.CharField(db_index=True, help_text='Unique Instagram media ID', max_length=100, unique=True)),
                ('username', models.CharField(help_text='Instagram username (without @)', max_length=100)),
                ('caption', models.TextField(blank=True, help_text='Post caption/description')),
                ('media_url', models.URLField(help_text='Primary image or video URL', max_length=500)),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('CAROUSEL_ALBUM', 'Carousel')], default='IMAGE', help_text='Type of media in the post', max_length=20)),
                ('permalink', models.URLField(help_text='Public URL to the post on Instagram', max_length=500)),
                ('posted_at', models.DateTimeField(db_index=True, help_text='When the post was published on Instagram')),
                ('last_fetched_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last time analytics were fetched')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created in PostFlow')),
                ('api_like_count', models.IntegerField(default=0, help_text='Total likes from API')),
                ('api_comments_count', models.IntegerField(default=0, help_text='Total comments count from API')),
                ('api_engagement', models.IntegerField(default=0, help_text='Engagement metric from Insights API (likes + comments)')),
                ('api_saved', models.IntegerField(default=0, help_text='Number of accounts that saved the post (Insights API)')),
                ('api_reach', models.IntegerField(default=0, help_text='Number of unique accounts that saw the post (Insights API)')),
                ('api_impressions', models.IntegerField(default=0, help_text='Total number of times post was seen (Insights API)')),
                ('api_video_views', models.IntegerField(blank=True, default=0, help_text='Video views for Reels (Insights API, null for non-video)', null=True)),
                ('account', models.ForeignKey(help_text='The Instagram Business account that posted this', on_delete=django.db.models.deletion.CASCADE, related_name='analytics_posts', to='instagram.instagrambusinessaccount')),
                ('scheduled_post', models.ForeignKey(blank=True, help_text='Linked ScheduledPost if this was created via PostFlow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instagram_analytics', to='postflow.scheduledpost')),
            ],
            options={
                'verbose_name': 'Instagram Post',
                'verbose_name_plural': 'Instagram Posts',
                'db_table': 'analytics_instagram_post',
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramEngagementSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_likes', models.IntegerField(db_index=True, default=0, help_text='Total number of likes (from API)')),
                ('total_comments', models.IntegerField(default=0, help_text='Total number of comments (from API)')),
                ('total_saved', models.IntegerField(default=0, help_text='Total number of saves (from API)')),
                ('total_engagement', models.IntegerField(db_index=True, default=0, help_text='Sum of likes + comments + saves (from API)')),
                ('total_reach', models.IntegerField(default=0, help_text='Number of unique accounts reached (from API)')),
                ('total_impressions', models.IntegerField(default=0, help_text='Total impressions (from API)')),
                ('total_video_views', models.IntegerField(blank=True, default=0, help_text='Total video views for Reels (from API)', null=True)),
                ('engagement_rate', models.FloatField(blank=True, help_text='Engagement rate percentage (engagement/impressions * 100)', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When these metrics were last updated')),
                ('post', models.OneToOneField(help_text='The post these metrics belong to', on_delete=django.db.models.deletion.CASCADE, related_name='engagement_summary', to='analytics_instagram.instagrampost')),
            ],
            options={
                'verbose_name': 'Instagram Engagement Summary',
                'verbose_name_plural': 'Instagram Engagement Summaries',
                'db_table': 'analytics_instagram_engagement_summary',
            },
        ),
        migrations.CreateModel(
            name='InstagramComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(db_index=True, help_text='Unique Instagram comment ID', max_length=100, unique=True)),
                ('username', models.CharField(help_text='Username of commenter (without @)', max_length=100)),
                ('text', models.TextField(help_text='Comment text content')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='When the comment was posted')),
                ('like_count', models.IntegerField(default=0, help_text='Number of likes on this comment')),
                ('parent_comment_id', models.CharField(blank=True, db_index=True, help_text='ID of parent comment (for threaded replies)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created in PostFlow')),
                ('post', models.ForeignKey(help_text='The post being commented on', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='analytics_instagram.instagrampost')),
            ],
            options={
                'verbose_name': 'Instagram Comment',
                'verbose_name_plural': 'Instagram Comments',
                'db_table': 'analytics_instagram_comment',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='instagrampost',
            index=models.Index(fields=['posted_at'], name='analytics_i_posted__111861_idx'),
        ),
        migrations.AddIndex(
            model_name='instagrampost',
            index=models.Index(fields=['last_fetched_at'], name='analytics_i_last_fe_81cd86_idx'),
        ),
        migrations.AddIndex(
            model_name='instagrampost',
            index=models.Index(fields=['account', 'posted_at'], name='analytics_i_account_00f06d_idx'),
        ),
        migrations.AddIndex(
            model_name='instagrampost',
            index=models.Index(fields=['media_type'], name='analytics_i_media_t_5f32e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='instagrampost',
            unique_together={('account', 'instagram_media_id')},
        ),
        migrations.AddIndex(
            model_name='instagramcomment',
            index=models.Index(fields=['timestamp'], name='analytics_i_timesta_49258c_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramcomment',
            index=models.Index(fields=['username'], name='analytics_i_usernam_17f07f_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramcomment',
            index=models.Index(fields=['parent_comment_id'], name='analytics_i_parent__a9b852_idx'),
        ),
    ]
