# Generated by Django 6.0.1 on 2026-01-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_instagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampost',
            name='media_url',
            field=models.URLField(help_text='Primary image or video URL', max_length=2048),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='permalink',
            field=models.URLField(help_text='Public URL to the post on Instagram', max_length=2048),
        ),
    ]
