# Generated by Django 6.0.1 on 2026-01-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_instagram', '0002_alter_instagrampost_media_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='cached_image',
            field=models.ImageField(blank=True, help_text='Cached copy of the media file stored in S3', null=True, upload_to='analytics/instagram/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='media_url',
            field=models.URLField(help_text='Primary image or video URL from Instagram API', max_length=2048),
        ),
    ]
