# Generated by Django 6.0.1 on 2026-02-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_instagram', '0003_instagrampost_cached_image_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='instagramcomment',
            index=models.Index(fields=['post', 'username'], name='analytics_i_post_id_9087a0_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramengagementsummary',
            index=models.Index(fields=['-total_engagement'], name='analytics_i_total_e_68d6be_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramengagementsummary',
            index=models.Index(fields=['-total_likes'], name='analytics_i_total_l_242b8e_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramengagementsummary',
            index=models.Index(fields=['-total_comments'], name='analytics_i_total_c_56aa7e_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramengagementsummary',
            index=models.Index(fields=['-total_saved'], name='analytics_i_total_s_b4d515_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramengagementsummary',
            index=models.Index(fields=['-total_reach'], name='analytics_i_total_r_90b799_idx'),
        ),
    ]
