# Generated by Django 5.2.7 on 2025-11-26 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postflow', '0022_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('mastodon', 'Mastodon'), ('pixelfed', 'Pixelfed')], help_text='Platform where the post was published', max_length=20)),
                ('platform_post_id', models.CharField(help_text='ID of the post on the platform', max_length=255)),
                ('likes', models.IntegerField(default=0, help_text='Number of likes/favorites')),
                ('comments', models.IntegerField(default=0, help_text='Number of comments/replies')),
                ('shares', models.IntegerField(default=0, help_text='Number of shares/reblogs (Mastodon/Pixelfed only)')),
                ('impressions', models.IntegerField(blank=True, help_text='Number of times the post was seen (Instagram only)', null=True)),
                ('reach', models.IntegerField(blank=True, help_text='Number of unique accounts reached (Instagram only)', null=True)),
                ('saved', models.IntegerField(default=0, help_text='Number of times the post was saved (Instagram only)')),
                ('engagement_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Engagement rate percentage (calculated field)', max_digits=5, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last time analytics were fetched')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this analytics record was created')),
                ('scheduled_post', models.ForeignKey(help_text='The post this analytics data belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='postflow.scheduledpost')),
            ],
            options={
                'verbose_name': 'Post Analytics',
                'verbose_name_plural': 'Post Analytics',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['scheduled_post', 'platform'], name='analytics_p_schedul_93a606_idx'), models.Index(fields=['last_updated'], name='analytics_p_last_up_de3676_idx')],
                'unique_together': {('scheduled_post', 'platform', 'platform_post_id')},
            },
        ),
    ]
