# Generated by Django 5.2.7 on 2026-01-27 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostAnalytics',
        ),
    ]
