# Generated by Django 5.2.7 on 2025-10-29 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MastodonAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_url', models.URLField(help_text='Mastodon or Pixelfed instance URL')),
                ('access_token', models.TextField(help_text='OAuth access token')),
                ('username', models.CharField(help_text='Mastodon username', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastodon_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
