# Generated by Django 6.0.1 on 2026-02-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelfed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastodonaccount',
            name='last_engagement_sync_at',
            field=models.DateTimeField(blank=True, help_text='When engagement data was last fetched for this account', null=True),
        ),
        migrations.AddField(
            model_name='mastodonaccount',
            name='last_posts_sync_at',
            field=models.DateTimeField(blank=True, help_text='When posts were last synced from this account', null=True),
        ),
        migrations.AddField(
            model_name='mastodonaccount',
            name='next_engagement_sync_at',
            field=models.DateTimeField(blank=True, help_text='When the next automatic engagement sync is scheduled', null=True),
        ),
        migrations.AddField(
            model_name='mastodonaccount',
            name='next_posts_sync_at',
            field=models.DateTimeField(blank=True, help_text='When the next automatic posts sync is scheduled', null=True),
        ),
    ]
