# Generated by Django 6.0.5 on 2026-07-29 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('plausible', 'Plausible Analytics'), ('gsc', 'Google Search Console'), ('ghost_admin', 'Ghost members / email stats')], max_length=30)),
                ('config', models.JSONField(blank=True, default=dict, help_text="Provider credentials/config, e.g. {'api_key': ..., 'site_id': ...}")),
                ('is_active', models.BooleanField(default=True)),
                ('last_collected_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_connections', to='websites.website')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('website', 'provider'), name='unique_provider_per_website')],
            },
        ),
        migrations.CreateModel(
            name='SiteSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('days', models.IntegerField(default=1, help_text='Collection window in days')),
                ('ghost', models.JSONField(blank=True, default=dict)),
                ('plausible', models.JSONField(blank=True, default=dict)),
                ('gsc', models.JSONField(blank=True, default=dict)),
                ('suggest', models.JSONField(blank=True, default=dict)),
                ('visitors', models.IntegerField(blank=True, null=True)),
                ('pageviews', models.IntegerField(blank=True, null=True)),
                ('subscribers', models.IntegerField(blank=True, help_text='Total newsletter members on this date', null=True)),
                ('subscriber_delta', models.IntegerField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_snapshots', to='websites.website')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('website', 'date'), name='unique_site_snapshot_per_day')],
            },
        ),
    ]
