# Generated by Django 6.0.5, hand-adjusted: Postgres needs an explicit USING
# cast for jsonb -> text, which plain AlterField does not emit.

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_site', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE analytics_site_analyticsconnection ALTER COLUMN config TYPE text USING config::text;',
                    reverse_sql='ALTER TABLE analytics_site_analyticsconnection ALTER COLUMN config TYPE jsonb USING config::jsonb;',
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='analyticsconnection',
                    name='config',
                    field=core.fields.EncryptedJSONField(blank=True, default=dict, help_text="Provider credentials/config, e.g. {'api_key': ..., 'site_id': ...}"),
                ),
            ],
        ),
    ]
