# Generated by Django 6.0.5 on 2026-07-29 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedInAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_urn', models.CharField(help_text='LinkedIn member URN, e.g. urn:li:person:xxxx', max_length=100)),
                ('username', models.CharField(blank=True, help_text='Display name', max_length=150)),
                ('access_token', models.TextField()),
                ('expires_at', models.DateTimeField(blank=True, help_text='LinkedIn tokens last ~60 days and cannot be auto-refreshed; re-auth needed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
