# Generated by Django 6.0.1 on 2026-01-27 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pixelfed', '0001_initial'),
        ('postflow', '0027_backfill_analytics_post_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='PixelfedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pixelfed_post_id', models.CharField(db_index=True, help_text='Unique Pixelfed post ID', max_length=100, unique=True)),
                ('instance_url', models.URLField(help_text='Pixelfed instance URL (e.g., https://pixelfed.social)', max_length=255)),
                ('username', models.CharField(help_text='Username of the poster (without @)', max_length=100)),
                ('caption', models.TextField(blank=True, help_text='Post caption/description')),
                ('media_url', models.URLField(help_text='Primary image or video URL', max_length=500)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('carousel', 'Carousel')], default='image', help_text='Type of media in the post', max_length=20)),
                ('post_url', models.URLField(help_text='Full URL to the post on Pixelfed', max_length=500)),
                ('posted_at', models.DateTimeField(db_index=True, help_text='When the post was published on Pixelfed')),
                ('last_fetched_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last time analytics were fetched')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created in PostFlow')),
                ('account', models.ForeignKey(help_text='The Pixelfed account that posted this', on_delete=django.db.models.deletion.CASCADE, related_name='analytics_posts', to='pixelfed.mastodonaccount')),
                ('scheduled_post', models.ForeignKey(blank=True, help_text='Linked ScheduledPost if this was created via PostFlow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pixelfed_analytics', to='postflow.scheduledpost')),
            ],
            options={
                'verbose_name': 'Pixelfed Post',
                'verbose_name_plural': 'Pixelfed Posts',
                'db_table': 'analytics_pixelfed_post',
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='PixelfedLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(help_text='Pixelfed account ID of the liker', max_length=100)),
                ('username', models.CharField(help_text='Username of the liker (without @)', max_length=100)),
                ('display_name', models.CharField(blank=True, help_text='Display name of the liker', max_length=200)),
                ('liked_at', models.DateTimeField(db_index=True, help_text='When the like occurred')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created in PostFlow')),
                ('post', models.ForeignKey(help_text='The post that was liked', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='analytics_pixelfed.pixelfedpost')),
            ],
            options={
                'verbose_name': 'Pixelfed Like',
                'verbose_name_plural': 'Pixelfed Likes',
                'db_table': 'analytics_pixelfed_like',
                'ordering': ['-liked_at'],
            },
        ),
        migrations.CreateModel(
            name='PixelfedEngagementSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_likes', models.IntegerField(db_index=True, default=0, help_text='Total number of likes')),
                ('total_comments', models.IntegerField(default=0, help_text='Total number of comments')),
                ('total_shares', models.IntegerField(default=0, help_text='Total number of shares')),
                ('total_engagement', models.IntegerField(db_index=True, default=0, help_text='Sum of likes + comments + shares')),
                ('engagement_rate', models.FloatField(blank=True, help_text='Engagement rate percentage (future: based on impressions)', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When these metrics were last updated')),
                ('post', models.OneToOneField(help_text='The post these metrics belong to', on_delete=django.db.models.deletion.CASCADE, related_name='engagement_summary', to='analytics_pixelfed.pixelfedpost')),
            ],
            options={
                'verbose_name': 'Pixelfed Engagement Summary',
                'verbose_name_plural': 'Pixelfed Engagement Summaries',
                'db_table': 'analytics_pixelfed_engagement_summary',
            },
        ),
        migrations.CreateModel(
            name='PixelfedComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(db_index=True, help_text='Unique Pixelfed comment ID', max_length=100, unique=True)),
                ('account_id', models.CharField(help_text='Pixelfed account ID of commenter', max_length=100)),
                ('username', models.CharField(help_text='Username of commenter (without @)', max_length=100)),
                ('display_name', models.CharField(blank=True, help_text='Display name of commenter', max_length=200)),
                ('content', models.TextField(help_text='Comment text content')),
                ('in_reply_to_id', models.CharField(blank=True, help_text='ID of parent comment (for threading)', max_length=100, null=True)),
                ('commented_at', models.DateTimeField(db_index=True, help_text='When the comment was posted')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created in PostFlow')),
                ('post', models.ForeignKey(help_text='The post being commented on', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='analytics_pixelfed.pixelfedpost')),
            ],
            options={
                'verbose_name': 'Pixelfed Comment',
                'verbose_name_plural': 'Pixelfed Comments',
                'db_table': 'analytics_pixelfed_comment',
                'ordering': ['commented_at'],
            },
        ),
        migrations.CreateModel(
            name='PixelfedShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(help_text='Pixelfed account ID of the sharer', max_length=100)),
                ('username', models.CharField(help_text='Username of the sharer (without @)', max_length=100)),
                ('display_name', models.CharField(blank=True, help_text='Display name of the sharer', max_length=200)),
                ('shared_at', models.DateTimeField(db_index=True, help_text='When the share occurred')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created in PostFlow')),
                ('post', models.ForeignKey(help_text='The post that was shared', on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='analytics_pixelfed.pixelfedpost')),
            ],
            options={
                'verbose_name': 'Pixelfed Share',
                'verbose_name_plural': 'Pixelfed Shares',
                'db_table': 'analytics_pixelfed_share',
                'ordering': ['-shared_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pixelfedpost',
            index=models.Index(fields=['posted_at'], name='analytics_p_posted__ad4374_idx'),
        ),
        migrations.AddIndex(
            model_name='pixelfedpost',
            index=models.Index(fields=['last_fetched_at'], name='analytics_p_last_fe_447aee_idx'),
        ),
        migrations.AddIndex(
            model_name='pixelfedpost',
            index=models.Index(fields=['account', 'posted_at'], name='analytics_p_account_0fe79e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pixelfedpost',
            unique_together={('instance_url', 'pixelfed_post_id')},
        ),
        migrations.AddIndex(
            model_name='pixelfedlike',
            index=models.Index(fields=['liked_at'], name='analytics_p_liked_a_fb56c7_idx'),
        ),
        migrations.AddIndex(
            model_name='pixelfedlike',
            index=models.Index(fields=['username'], name='analytics_p_usernam_a5f216_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pixelfedlike',
            unique_together={('post', 'account_id')},
        ),
        migrations.AddIndex(
            model_name='pixelfedcomment',
            index=models.Index(fields=['commented_at'], name='analytics_p_comment_0b9ef9_idx'),
        ),
        migrations.AddIndex(
            model_name='pixelfedcomment',
            index=models.Index(fields=['username'], name='analytics_p_usernam_2911a8_idx'),
        ),
        migrations.AddIndex(
            model_name='pixelfedcomment',
            index=models.Index(fields=['in_reply_to_id'], name='analytics_p_in_repl_ea59f0_idx'),
        ),
        migrations.AddIndex(
            model_name='pixelfedshare',
            index=models.Index(fields=['shared_at'], name='analytics_p_shared__f3b789_idx'),
        ),
        migrations.AddIndex(
            model_name='pixelfedshare',
            index=models.Index(fields=['username'], name='analytics_p_usernam_9f1c5d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pixelfedshare',
            unique_together={('post', 'account_id')},
        ),
    ]
