# Generated by Django 6.0.1 on 2026-01-29 13:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_pixelfed', '0001_initial'),
        ('pixelfed', '0001_initial'),
        ('postflow', '0027_backfill_analytics_post_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixelfedlike',
            name='first_seen_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When we first discovered this like (for timeline estimation)'),
        ),
        migrations.AddField(
            model_name='pixelfedpost',
            name='api_favourites_count',
            field=models.IntegerField(default=0, help_text='Favorite/like count from API Status object'),
        ),
        migrations.AddField(
            model_name='pixelfedpost',
            name='api_reblogs_count',
            field=models.IntegerField(default=0, help_text='Reblog/share count from API Status object'),
        ),
        migrations.AddField(
            model_name='pixelfedpost',
            name='api_replies_count',
            field=models.IntegerField(default=0, help_text='Reply count from API Status object'),
        ),
        migrations.AddField(
            model_name='pixelfedpost',
            name='edited_at',
            field=models.DateTimeField(blank=True, help_text='When the post was last edited (if edited)', null=True),
        ),
        migrations.AddField(
            model_name='pixelfedpost',
            name='in_reply_to_account_id',
            field=models.CharField(blank=True, help_text='Parent post author account ID', max_length=100),
        ),
        migrations.AddField(
            model_name='pixelfedpost',
            name='in_reply_to_id',
            field=models.CharField(blank=True, help_text='Parent post ID if this is a reply', max_length=100),
        ),
        migrations.AddField(
            model_name='pixelfedpost',
            name='language',
            field=models.CharField(blank=True, help_text='ISO 639-1 language code', max_length=10),
        ),
        migrations.AddField(
            model_name='pixelfedpost',
            name='sensitive',
            field=models.BooleanField(default=False, help_text='Whether content has a content warning'),
        ),
        migrations.AddField(
            model_name='pixelfedpost',
            name='spoiler_text',
            field=models.CharField(blank=True, help_text='Content warning text', max_length=500),
        ),
        migrations.AddField(
            model_name='pixelfedpost',
            name='visibility',
            field=models.CharField(default='public', help_text='Post visibility: public, unlisted, private, or direct', max_length=20),
        ),
        migrations.AddField(
            model_name='pixelfedshare',
            name='first_seen_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When we first discovered this share (for timeline estimation)'),
        ),
        migrations.AlterField(
            model_name='pixelfedlike',
            name='liked_at',
            field=models.DateTimeField(db_index=True, help_text='When the like occurred (estimated as first discovered time)'),
        ),
        migrations.AlterField(
            model_name='pixelfedshare',
            name='shared_at',
            field=models.DateTimeField(db_index=True, help_text='When the share occurred (estimated as first discovered time)'),
        ),
        migrations.AddIndex(
            model_name='pixelfedlike',
            index=models.Index(fields=['first_seen_at'], name='analytics_p_first_s_805819_idx'),
        ),
        migrations.AddIndex(
            model_name='pixelfedpost',
            index=models.Index(fields=['visibility'], name='analytics_p_visibil_57f185_idx'),
        ),
        migrations.AddIndex(
            model_name='pixelfedpost',
            index=models.Index(fields=['in_reply_to_id'], name='analytics_p_in_repl_c7ceed_idx'),
        ),
        migrations.AddIndex(
            model_name='pixelfedshare',
            index=models.Index(fields=['first_seen_at'], name='analytics_p_first_s_ec145c_idx'),
        ),
    ]
