# Generated by Django 6.0.1 on 2026-01-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_pixelfed', '0002_expand_analytics_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixelfedpost',
            name='in_reply_to_account_id',
            field=models.CharField(blank=True, null=True, help_text='Parent post author account ID', max_length=100),
        ),
    ]
