# Generated by Django 6.0.1 on 2026-01-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_pixelfed', '0003_fix_in_reply_to_account_id_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixelfedpost',
            name='in_reply_to_id',
            field=models.CharField(blank=True, help_text='Parent post ID if this is a reply', max_length=100, null=True),
        ),
    ]
