# Generated by Django 6.0.1 on 2026-01-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_pixelfed', '0004_fix_in_reply_to_id_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixelfedpost',
            name='language',
            field=models.CharField(blank=True, help_text='ISO 639-1 language code', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pixelfedpost',
            name='spoiler_text',
            field=models.CharField(blank=True, help_text='Content warning text', max_length=500, null=True),
        ),
    ]
