# Generated by Django 6.0.1 on 2026-02-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_pixelfed', '0005_fix_nullable_charfields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pixelfedcomment',
            index=models.Index(fields=['post', 'username'], name='analytics_p_post_id_21af54_idx'),
        ),
        migrations.AddIndex(
            model_name='pixelfedengagementsummary',
            index=models.Index(fields=['-total_engagement'], name='analytics_p_total_e_216e65_idx'),
        ),
        migrations.AddIndex(
            model_name='pixelfedengagementsummary',
            index=models.Index(fields=['-total_likes'], name='analytics_p_total_l_fd345d_idx'),
        ),
        migrations.AddIndex(
            model_name='pixelfedengagementsummary',
            index=models.Index(fields=['-total_comments'], name='analytics_p_total_c_c3ecec_idx'),
        ),
        migrations.AddIndex(
            model_name='pixelfedengagementsummary',
            index=models.Index(fields=['-total_shares'], name='analytics_p_total_s_b6ac6a_idx'),
        ),
        migrations.AddIndex(
            model_name='pixelfedlike',
            index=models.Index(fields=['post', 'username'], name='analytics_p_post_id_35bdf1_idx'),
        ),
        migrations.AddIndex(
            model_name='pixelfedshare',
            index=models.Index(fields=['post', 'username'], name='analytics_p_post_id_bd4e9b_idx'),
        ),
    ]
