# Generated by Django 6.0.5 on 2026-07-29 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postflow', '0034_add_deleted_status'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('goal', models.CharField(choices=[('new_issue', 'Promote new post'), ('evergreen', 'Evergreen re-promotion')], default='new_issue', max_length=20)),
                ('utm_campaign', models.SlugField(help_text='utm_campaign value used on all links in this campaign', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('done', 'Done')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='websites.blogpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='websites.website')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=30)),
                ('model_used', models.CharField(max_length=100)),
                ('prompt_version', models.CharField(default='v1', max_length=50)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='campaigns.campaign')),
                ('scheduled_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_draft', to='postflow.scheduledpost')),
            ],
        ),
        migrations.CreateModel(
            name='VoiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('rules', models.TextField(help_text='Markdown instructions describing the writing voice and platform rules')),
                ('platform_notes', models.JSONField(blank=True, default=dict, help_text='Optional per-platform overrides, keyed by platform')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_profiles', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(blank=True, help_text='Optional: scope this profile to one website', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_profiles', to='websites.website')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('report_markdown', models.TextField()),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_reports', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_reports', to='websites.website')),
            ],
            options={
                'ordering': ['-week_start'],
                'constraints': [models.UniqueConstraint(fields=('user', 'website', 'week_start'), name='unique_report_per_week')],
            },
        ),
    ]
