# Generated by Django 6.0.5 on 2026-07-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='rationale',
            field=models.TextField(blank=True, default='', help_text='Why the autopilot planned this campaign (shown in the review queue)'),
        ),
    ]
