# Generated by Django 6.0.5 on 2026-07-29 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postflow', '0034_add_deleted_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlassAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glass_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManualPostTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='glass', max_length=30)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for schedule'), ('ready', 'Ready to post'), ('posted', 'Posted'), ('skipped', 'Skipped')], default='waiting', max_length=20)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('posted_url', models.URLField(blank=True, help_text='Optional link to the published post')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_tasks', to='postflow.scheduledpost')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
