# Generated by Django 6.0.1 on 2026-02-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrambusinessaccount',
            name='last_insights_sync_at',
            field=models.DateTimeField(blank=True, help_text='When insights data was last fetched for this account', null=True),
        ),
        migrations.AddField(
            model_name='instagrambusinessaccount',
            name='last_posts_sync_at',
            field=models.DateTimeField(blank=True, help_text='When posts were last synced from this account', null=True),
        ),
        migrations.AddField(
            model_name='instagrambusinessaccount',
            name='next_insights_sync_at',
            field=models.DateTimeField(blank=True, help_text='When the next automatic insights sync is scheduled', null=True),
        ),
        migrations.AddField(
            model_name='instagrambusinessaccount',
            name='next_posts_sync_at',
            field=models.DateTimeField(blank=True, help_text='When the next automatic posts sync is scheduled', null=True),
        ),
    ]
