# Generated by Django 6.0.5 on 2026-07-29 09:11

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_add_sync_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrambusinessaccount',
            name='access_token',
            field=core.fields.EncryptedTextField(help_text='Page access token with access to IG account'),
        ),
    ]
