# Generated by Django 5.1.3 on 2025-01-02 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postflow', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
