# Generated by Django 5.1.3 on 2025-01-08 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postflow', '0003_remove_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name of the hashtag (e.g., #example)', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name of the tag group', max_length=255)),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags associated with this group', related_name='tag_groups', to='postflow.tag')),
                ('user', models.ForeignKey(help_text='User who owns this tag group', on_delete=django.db.models.deletion.CASCADE, related_name='tag_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'user')},
            },
        ),
    ]
