# Generated by Django 5.1.3 on 2025-01-30 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postflow', '0005_tag_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'user')},
        ),
    ]
