# Generated by Django 5.1.3 on 2025-01-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postflow', '0006_alter_tag_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='taggroup',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, help_text='Name of the hashtag (e.g., #example)', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='unique_tag_per_user'),
        ),
        migrations.AddConstraint(
            model_name='taggroup',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='unique_group_per_user'),
        ),
    ]
