# Generated by Django 5.1.6 on 2025-02-14 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postflow', '0007_alter_tag_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MastodonAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_url', models.URLField(help_text='Mastodon or Pixelfed instance URL')),
                ('access_token', models.CharField(help_text='OAuth access token', max_length=512)),
                ('username', models.CharField(help_text='Mastodon username', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastodon_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
