# Generated by Django 5.1.6 on 2025-02-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postflow', '0008_mastodonaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastodonaccount',
            name='access_token',
            field=models.TextField(help_text='OAuth access token'),
        ),
    ]
