# Generated by Django 5.1.6 on 2025-02-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postflow', '0010_scheduledpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='user_timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
