# Generated by Django 5.1.6 on 2025-05-15 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postflow', '0012_scheduledpost_mastodon_media_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramBusinessAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('access_token', models.TextField(help_text='Page access token with access to IG account')),
                ('page_id', models.CharField(help_text='Facebook Page ID linked to IG account', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_business_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
