# Generated by Django 5.1.6 on 2025-05-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postflow', '0013_instagrambusinessaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagrambusinessaccount',
            name='page_id',
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='instagram_accounts',
            field=models.ManyToManyField(blank=True, to='postflow.instagrambusinessaccount'),
        ),
    ]
