# Generated by Django 5.1.6 on 2025-08-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postflow', '0014_remove_instagrambusinessaccount_page_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrambusinessaccount',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagrambusinessaccount',
            name='last_refreshed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
