# Generated by Django 5.2.7 on 2025-10-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postflow', '0016_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='instagram_media_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
