# Generated by Django 5.2.7 on 2025-10-29 20:26
# NOTE: This migration had issues on production. It's now a no-op.
# The actual schema changes are handled in 0019_resolve_refactoring_migration
# Servers that already applied this migration will continue to work.
# Servers that haven't applied it yet will skip this and apply 0019 instead.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
        ('pixelfed', '0001_initial'),
        ('postflow', '0017_scheduledpost_instagram_media_id'),
    ]

    operations = [
        # This migration is now a no-op.
        # The original operations tried to delete models that don't exist,
        # causing errors on production. See migration 0019 for the proper fix.
    ]
