# Generated by Django 5.2.7 on 2025-10-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
        ('pixelfed', '0001_initial'),
        ('postflow', '0017_scheduledpost_instagram_media_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastodonaccount',
            name='user',
        ),
        migrations.AlterField(
            model_name='scheduledpost',
            name='instagram_accounts',
            field=models.ManyToManyField(blank=True, to='instagram.instagrambusinessaccount'),
        ),
        migrations.AlterField(
            model_name='scheduledpost',
            name='mastodon_accounts',
            field=models.ManyToManyField(blank=True, to='pixelfed.mastodonaccount'),
        ),
        migrations.DeleteModel(
            name='InstagramBusinessAccount',
        ),
        migrations.DeleteModel(
            name='MastodonAccount',
        ),
    ]
