# Generated by Django 5.2.7 on 2025-11-26 21:01

from django.db import migrations
import postflow.models


class Migration(migrations.Migration):

    dependencies = [
        ('postflow', '0023_add_platform_post_ids'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', postflow.models.CustomUserManager()),
            ],
        ),
    ]
