# Generated by Django 5.2.7 on 2025-11-26 21:02
# This migration removes InstagramBusinessAccount and MastodonAccount from
# postflow's migration state only, without touching the database.
# These models were refactored into separate apps (instagram, mastodon_native)
# in migrations 0018-0020, but were never removed from the migration state.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postflow', '0024_add_custom_user_manager'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='InstagramBusinessAccount',
                ),
                migrations.DeleteModel(
                    name='MastodonAccount',
                ),
            ],
            database_operations=[
                # No database operations - tables already exist in other apps
            ],
        ),
    ]
