# Generated by Django 5.2.7 on 2025-11-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelfed', '0001_initial'),
        ('postflow', '0025_remove_refactored_models_from_state'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='scheduledpost',
            name='instagram_post_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledpost',
            name='mastodon_accounts',
            field=models.ManyToManyField(blank=True, help_text='Pixelfed/Mastodon-compatible instances', to='pixelfed.mastodonaccount'),
        ),
        migrations.AlterField(
            model_name='scheduledpost',
            name='pixelfed_post_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
