# Generated by Django 5.2.7 on 2025-11-26 21:10
# This migration backfills analytics post IDs from existing media IDs
# for posts that were published before the analytics feature was added.

from django.db import migrations


def backfill_post_ids(apps, schema_editor):
    """
    Backfill instagram_post_id and pixelfed_post_id from existing data.

    - instagram_post_id: Copy from instagram_media_id (same value)
    - pixelfed_post_id: Copy from mastodon_post_id (for Pixelfed posts)
    """
    ScheduledPost = apps.get_model('postflow', 'ScheduledPost')

    # Backfill instagram_post_id from instagram_media_id
    instagram_posts = ScheduledPost.objects.filter(
        instagram_media_id__isnull=False,
        instagram_post_id__isnull=True
    )
    instagram_count = instagram_posts.count()

    for post in instagram_posts:
        post.instagram_post_id = post.instagram_media_id
        post.save(update_fields=['instagram_post_id'])

    # Backfill pixelfed_post_id from mastodon_post_id
    # (Pixelfed posts store their ID in mastodon_post_id)
    pixelfed_posts = ScheduledPost.objects.filter(
        mastodon_post_id__isnull=False,
        pixelfed_post_id__isnull=True
    ).prefetch_related('mastodon_accounts')

    pixelfed_count = 0
    for post in pixelfed_posts:
        # Only copy if this post has Pixelfed accounts
        if post.mastodon_accounts.exists():
            post.pixelfed_post_id = post.mastodon_post_id
            post.save(update_fields=['pixelfed_post_id'])
            pixelfed_count += 1

    print(f"Backfilled {instagram_count} Instagram post IDs and {pixelfed_count} Pixelfed post IDs")


def reverse_backfill(apps, schema_editor):
    """Reverse is not needed - we're just copying data"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('postflow', '0026_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_post_ids, reverse_backfill),
    ]
