# Generated by Django 6.0.1 on 2026-05-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postflow', '0027_backfill_analytics_post_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='pinned',
            field=models.BooleanField(default=False, help_text="If true, always included when this tag's group is selected"),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, help_text="Hashtag stored without # prefix (e.g., 'example')", max_length=255),
        ),
    ]
