# Generated by Django 6.0.1 on 2026-05-06 13:44

from django.db import migrations


def normalize_hashtags(apps, schema_editor):
    """Strip # prefix from all existing tags and merge duplicates."""
    Tag = apps.get_model("postflow", "Tag")
    for tag in Tag.objects.all():
        normalized = tag.name.lstrip("#").strip().lower()
        if normalized != tag.name:
            # Check if a normalized version already exists for this user
            existing = Tag.objects.filter(name=normalized, user=tag.user).exclude(pk=tag.pk).first()
            if existing:
                # Merge: move all tag_group associations to the existing tag, then delete duplicate
                for group in tag.tag_groups.all():
                    group.tags.add(existing)
                    group.tags.remove(tag)
                tag.delete()
            else:
                tag.name = normalized
                tag.save(update_fields=["name"])


def reverse_normalize(apps, schema_editor):
    """Add # prefix back to all tags."""
    Tag = apps.get_model("postflow", "Tag")
    for tag in Tag.objects.all():
        if not tag.name.startswith("#"):
            tag.name = f"#{tag.name}"
            tag.save(update_fields=["name"])


class Migration(migrations.Migration):

    dependencies = [
        ('postflow', '0028_add_tag_pinned_field'),
    ]

    operations = [
        migrations.RunPython(normalize_hashtags, reverse_normalize),
    ]
