# Generated by Django 6.0.1 on 2026-05-06 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postflow', '0029_normalize_existing_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='alt_text',
            field=models.TextField(blank=True, default='', help_text='Alt text for accessibility (passed to all platforms)'),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='collaborators',
            field=models.CharField(blank=True, default='', help_text='Comma-separated Instagram collaborator usernames (max 3)', max_length=500),
        ),
        migrations.AlterField(
            model_name='scheduledpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('scheduled', 'Scheduled'), ('posted', 'Posted'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='HashtagUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='all', max_length=20)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtag_usages', to='postflow.scheduledpost')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='postflow.tag')),
            ],
            options={
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('facebook_page_id', models.CharField(help_text='Facebook Places page ID for Instagram API', max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('use_count', models.PositiveIntegerField(default=0, help_text='Track usage for frequently-used sorting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-use_count', 'name'],
            },
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Location tag for Instagram posts', null=True, on_delete=django.db.models.deletion.SET_NULL, to='postflow.location'),
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Username to tag (e.g., @user or @user@instance)', max_length=255)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('mastodon', 'Mastodon'), ('pixelfed', 'Pixelfed')], default='instagram', max_length=20)),
                ('x', models.FloatField(blank=True, help_text='X position (0-1) for Instagram image tags', null=True)),
                ('y', models.FloatField(blank=True, help_text='Y position (0-1) for Instagram image tags', null=True)),
                ('post_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tags', to='postflow.postimage')),
                ('scheduled_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tags', to='postflow.scheduledpost')),
            ],
            options={
                'verbose_name': 'User Tag',
                'verbose_name_plural': 'User Tags',
            },
        ),
        migrations.CreateModel(
            name='DefaultTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('mastodon', 'Mastodon'), ('pixelfed', 'Pixelfed')], default='instagram', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'username', 'platform'), name='unique_default_tag')],
            },
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('facebook_page_id', 'user'), name='unique_location_per_user'),
        ),
    ]
