# Generated by Django 6.0.1 on 2026-05-06 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_add_sync_timestamps'),
        ('mastodon_native', '0002_add_sync_timestamps'),
        ('pixelfed', '0002_add_sync_timestamps'),
        ('postflow', '0030_phase1_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField(help_text='Use {title}, {description}, {date} as placeholders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caption_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-use_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_caption_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='postflow.captiontemplate')),
                ('default_hashtag_groups', models.ManyToManyField(blank=True, related_name='+', to='postflow.taggroup')),
                ('default_instagram_accounts', models.ManyToManyField(blank=True, related_name='+', to='instagram.instagrambusinessaccount')),
                ('default_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='postflow.location')),
                ('default_mastodon_accounts', models.ManyToManyField(blank=True, related_name='+', to='pixelfed.mastodonaccount')),
                ('default_mastodon_native_accounts', models.ManyToManyField(blank=True, related_name='+', to='mastodon_native.mastodonaccount')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='posting_defaults', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Defaults',
            },
        ),
        migrations.AddConstraint(
            model_name='captiontemplate',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='unique_template_per_user'),
        ),
    ]
