# Generated by Django 6.0.5 on 2026-05-06 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_add_sync_timestamps'),
        ('mastodon_native', '0002_add_sync_timestamps'),
        ('pixelfed', '0002_add_sync_timestamps'),
        ('postflow', '0031_caption_templates_and_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='delete_after_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Auto-delete post after N hours (Mastodon/Pixelfed only)', null=True),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='language',
            field=models.CharField(blank=True, default='', help_text='ISO 639-1 language code (e.g. en, es, de). Used on Mastodon/Pixelfed.', max_length=10),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='spoiler_text',
            field=models.CharField(blank=True, default='', help_text='Content warning text (Mastodon/Pixelfed CW). Ignored on Instagram.', max_length=500),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='thread_order',
            field=models.PositiveIntegerField(default=0, help_text='Order within thread (0 = first post)'),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Followers only'), ('direct', 'Direct message')], default='public', help_text='Post visibility on Mastodon/Pixelfed. Instagram is always public.', max_length=20),
        ),
        migrations.CreateModel(
            name='RSSFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Label for this feed', max_length=255)),
                ('url', models.URLField(help_text='RSS/Atom feed URL')),
                ('caption_template', models.TextField(default='{title}\n\n{url}', help_text='Template for post caption. Variables: {title}, {url}, {summary}, {author}')),
                ('is_active', models.BooleanField(default=True)),
                ('include_instagram', models.BooleanField(default=False, help_text='Also post to Instagram accounts')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_entry_guid', models.CharField(blank=True, default='', help_text='GUID of last processed entry', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instagram_accounts', models.ManyToManyField(blank=True, to='instagram.instagrambusinessaccount')),
                ('mastodon_accounts', models.ManyToManyField(blank=True, to='pixelfed.mastodonaccount')),
                ('mastodon_native_accounts', models.ManyToManyField(blank=True, to='mastodon_native.mastodonaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rss_feeds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledBoost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_url', models.URLField(help_text='URL of the status to boost')),
                ('status_id', models.CharField(blank=True, default='', help_text='Resolved status ID on target instance', max_length=255)),
                ('boost_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('posted', 'Posted'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mastodon_accounts', models.ManyToManyField(blank=True, to='pixelfed.mastodonaccount')),
                ('mastodon_native_accounts', models.ManyToManyField(blank=True, to='mastodon_native.mastodonaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_boosts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['boost_date'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text='Internal label for this thread', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='thread',
            field=models.ForeignKey(blank=True, help_text='Thread this post belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='postflow.scheduledthread'),
        ),
        migrations.CreateModel(
            name='FollowerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('pixelfed', 'Pixelfed'), ('mastodon', 'Mastodon'), ('mastodon_native', 'Mastodon (Native)'), ('instagram', 'Instagram')], max_length=20)),
                ('account_username', models.CharField(max_length=255)),
                ('instance_url', models.URLField(blank=True, default='')),
                ('date', models.DateField(db_index=True)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('following_count', models.PositiveIntegerField(default=0)),
                ('posts_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'platform', 'account_username', 'date'), name='unique_snapshot_per_day')],
            },
        ),
    ]
