# Generated by Django 6.0.5 on 2026-05-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postflow', '0032_fediverse_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='poll_expires_in',
            field=models.PositiveIntegerField(blank=True, help_text='Poll duration in seconds (e.g. 86400 for 24h)', null=True),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='poll_hide_totals',
            field=models.BooleanField(default=False, help_text='Hide vote totals until poll ends'),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='poll_multiple',
            field=models.BooleanField(default=False, help_text='Allow multiple poll choices'),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='poll_options',
            field=models.JSONField(blank=True, help_text="Poll options as JSON list, e.g. ['Option A', 'Option B']", null=True),
        ),
    ]
