# Generated by Django 6.0.5 on 2026-05-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postflow', '0033_add_poll_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('scheduled', 'Scheduled'), ('posted', 'Posted'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='pending', max_length=20),
        ),
    ]
