# Generated by Django 6.0.5 on 2026-07-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glass', '0001_initial'),
        ('linkedin', '0001_initial'),
        ('postflow', '0034_add_deleted_status'),
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='glass_accounts',
            field=models.ManyToManyField(blank=True, to='glass.glassaccount'),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='linkedin_accounts',
            field=models.ManyToManyField(blank=True, to='linkedin.linkedinaccount'),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='linkedin_post_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='threads_accounts',
            field=models.ManyToManyField(blank=True, to='threads.threadsaccount'),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='threads_post_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdefaults',
            name='default_glass_accounts',
            field=models.ManyToManyField(blank=True, related_name='+', to='glass.glassaccount'),
        ),
        migrations.AddField(
            model_name='userdefaults',
            name='default_linkedin_accounts',
            field=models.ManyToManyField(blank=True, related_name='+', to='linkedin.linkedinaccount'),
        ),
        migrations.AddField(
            model_name='userdefaults',
            name='default_threads_accounts',
            field=models.ManyToManyField(blank=True, related_name='+', to='threads.threadsaccount'),
        ),
        migrations.AlterField(
            model_name='scheduledpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('scheduled', 'Scheduled'), ('awaiting_manual', 'Awaiting manual post'), ('posted', 'Posted'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='pending', max_length=20),
        ),
    ]
